import { Collection } from "@types";

export const collections: Collection[] = [
  {
    id: 0,
    name: "Coyote",
    color: "#356551",
    banner: "/images/banner/coyote.png",
    desktop: "/images/desktop/coyote.png",
    mobile: "/images/mobile/coyote.png",
    pfp: "/images/pfp/coyote.png",
  },
  {
    id: 1,
    name: "El Guapo",
    color: "#FE6B2F",
    banner: "/images/banner/el-guapo.png",
    desktop: "/images/desktop/el-guapo.png",
    mobile: "/images/mobile/el-guapo.png",
    pfp: "/images/pfp/el-guapo.png",
  },
  {
    id: 2,
    name: "Mayahuel",
    color: "#90CFBC",
    banner: "/images/banner/mayahuel.png",
    desktop: "/images/desktop/mayahuel.png",
    mobile: "/images/mobile/mayahuel.png",
    pfp: "/images/pfp/mayahuel.png",
  },
  {
    id: 3,
    name: "Smiley",
    color: "#5A4E42",
    banner: "/images/banner/smiley.png",
    desktop: "/images/desktop/smiley.png",
    mobile: "/images/mobile/smiley.png",
    pfp: "/images/pfp/smiley.png",
  },
  {
    id: 4,
    name: "Wednesday",
    color: "#81a2e8",
    banner: "/images/banner/wednesday.png",
    desktop: "/images/desktop/wednesday.png",
    mobile: "/images/mobile/wednesday.png",
    pfp: "/images/pfp/wednesday.png",
  },
  {
    id:5,
    name: "Thumper",
    color: "#2A4F43",
    banner: "/images/banner/thumper.png",
    desktop: "/images/desktop/thumper.png",
    mobile: "/images/mobile/thumper.png",
    pfp: "/images/pfp/thumper.png",
  },
];