import { Collection } from "@types";

export const collection: Collection[] = [
  {
    id: 0,
    name: "Scum",
    tag: "scum",
    color: "#B3CCC3",
    topValue: -90,
    mintAddress: "7fbbpVBnqhYeDbNRmYZ6R18FzWgesX9Ks94oooxJgNu9",
  },
  {
    id: 1,
    name: "Coyote",
    tag: "coyote",
    color: "#356551",
    topValue: 50,
    mintAddress: "F1XAgf3FPQNNQ3aVows48RH2ShwYrGxfSYYbDApAAjCN",
  },
  {
    id: 2,
    name: "El Guapo",
    tag: "el-guapo",
    color: "#FE6B2F",
    topValue: -80,
    mintAddress: "J8oj2EudAry8bxCudxo1yXxVCTBtW954M1Ph5areu4iM",
  },
  {
    id: 3,
    name: "Mayahuel",
    tag: "mayahuel",
    color: "#90CFBC",
    topValue: 140,
    mintAddress: "uqNRKUoQJdUYPzWhz9uuCZAXWsPU5A5SoU7qYjuCYQF",
  },
  {
    id: 4,
    name: "Smiley",
    tag: "smiley",
    color: "#5A4E42",
    topValue: -60,
    mintAddress: "CwnG1kRzJN7GwcziQo4Hx1pbSQmnBMuy6mwcWFmg9ynw",
  },
  {
    id: 5,
    name: "Wednesday",
    tag: "wednesday",
    color: "#81a2e8",
    topValue: 160,
    mintAddress: "8ZDf1adDisgDrKp8nJccQ98LF22FkuDq1Vek1b8YsLY",
  },
  {
    id: 6,
    name: "Thumper",
    tag: "thumper",
    color: "#2A4F43",
    topValue: 80,
    mintAddress: "GX6XWg6vJ7iW1H6kR9q8TTG3E1xRzRCyeYTnNckpYBTS",
  },
  {
    id: 7,
    name: "Junior",
    tag: "junior",
    color: "#333333",
    doublePfp: true,
    topValue: -80,
    mintAddress: "5wUmNTLcH7wWhU9GvgYRydtcaEdBvGbaqDSwk5Xhgj2D",
  },
  {
    id: 8,
    name: "Temper",
    tag: "temper",
    color: "#FBC6B0",
    topValue: -70,
    mintAddress: "EMmTa2PwfCvpu6ZpwRtWVZ4B8mojw2WbJUdoJX68A8oB",
  },
  {
    id: 9,
    name: "Zeke",
    tag: "zeke",
    color: "#8D9FC3",
    topValue: 80,
    mintAddress: "G4ZRCjbvTqdWRBG7ZU4Wmo6bimbvQSVn7GfF3f7vQzH5",
  },
  {
    id: 10,
    name: "Rabbit",
    tag: "rabbit",
    color: "#D5738F",
    topValue: -65,
    mintAddress: "D4ABjRYWFopTKWxnsYbhL3KKALcCjs5UJn7yZXWVaoSB",
  },
  {
    id: 11,
    name: "Flea",
    tag: "flea",
    color: "#555647",
    topValue: 140,
    mintAddress: "3SeqwjmtXHhzupPoMfQMVBYEghaAYksCY8jaYG7WJ5DV",
  },
  {
    id: 12,
    name: "Lindo",
    tag: "lindo",
    color: "#B93D29",
    topValue: 80,
    mintAddress: "4eb1TajEfpRngXLCdRgn9sMSYvKPWM1jW87TEHRjQ1e1",
  },
  {
    id: 13,
    name: "Nacho",
    tag: "nacho",
    color: "#8BD3D5",
    topValue: 190,
    mintAddress: "GKYxNwdUbE6cuYx6S7PABemVvvzFNEbwGzmAbCEdEqX3",
  },
  {
    id: 14,
    name: "Canelo",
    tag: "canelo",
    color: "#FFB969",
    topValue: -90,
    mintAddress: "BJERNpc7vEM8aiZjkq7os4K3zVKWVtXjmFdfQamCPXdQ",
  },
  {
    id: 15,
    name: "El Santo",
    tag: "el-santo",
    color: "#3969A2",
    topValue: -100,
    mintAddress: "F49BxnaUJeGRnb3kAxqLyRTiQ9MVKZr8HQhME6AHyxjw",
  },
  {
    id: 16,
    name: "Lobo",
    tag: "lobo",
    color: "#FFB969",
    topValue: 60,
    mintAddress: "8eDha6YyBihJ8Ufq2SiEB88VewSmoFVfb2GCLrYiwmkV",
  },
  {
    id: 17,
    name: "Sonny",
    tag: "sonny",
    color: "#243250",
    topValue: -80,
    mintAddress: "8pyv7FpMa91iJLwiEC3stBH7uewUFNq5p8nd25HcbnQk",
  },
  {
    id: 18,
    name: "Chido",
    tag: "chido",
    color: "#251C18",
    doublePfp: true,
    topValue: 120,
    mintAddress: "4JGxTczAPU2x4c7mAEMzweBwWSvwrZTV2KtQnLqFgkhN",
  },
  {
    id: 19,
    name: "Flaco",
    tag: "flaco",
    color: "#FFCC00",
    topValue: 200,
    mintAddress: "3voFwtNFSSPjfmAcPxSi9FmtU3DcA5Wc4Bn3F3h2zcU6",
  },
  {
    id: 20,
    name: "Pablo",
    tag: "pablo",
    color: "#1E2738",
    topValue: -40,
    mintAddress: "8Qraa9JYsDVZgBuaVEmUuwoHwQMaXdgSqksvim59jd9P",
  },
  {
    id: 21,
    name: "Kahlo",
    tag: "kahlo",
    color: "#B7765B",
    topValue: -90,
    mintAddress: "59ir4HEsTCeEk3EpkTNECg2JCuxN3KWwEeEUC3QzLbvU",
  },
  {
    id: 22,
    name: "Santi",
    tag: "santi",
    color: "#F76C31",
    topValue: 90,
    mintAddress: "2uAGapxfHT42psiLu5U3SzZQ9hyvVCYx6oTdaWqjE564",
  },
  {
    id: 23,
    name: "Xolo",
    tag: "xolo",
    color: "#552433",
    topValue: -40,
    mintAddress: "3XJhT7u9oHiXB77fLf6w5sHMa1aZrXSkALoV46XitJbD",
  },
  {
    id: 24,
    name: "Kai",
    tag: "kai",
    color: "#58C1BF",
    topValue: 40,
    mintAddress: "GhfmfuTG4zqtf1bPuJA655jgM1DSaMQyhq6wttsc4m29",
  },
  {
    id: 25,
    name: "Angel",
    tag: "angel",
    color: "#FE9064",
    topValue: -40,
    mintAddress: "A8tfprbYBR6QMDmvfDDUdXVzc75tc2Kc7vteUetx2Acm",
  },
  // {
  //   id:26,
  //   name: "Dark Kai",
  //   tag: "dark-kai",
  //   color: "#242424",
  //   topValue: 0,
  // },
];
