import { Collection } from "@types";

export const collections: Collection[] = [
  {
    id: 0,
    name: "Coyote",
    tag: "coyote",
    color: "#356551", 
    topValue: -50,
  },
  {
    id: 1,
    name: "El Guapo",
    tag: "el-guapo",
    color: "#FE6B2F",
    topValue: -80,
  },
  {
    id: 2,
    name: "Mayahuel",
    tag: "mayahuel",
    color: "#90CFBC",
    topValue: 140,
  },
  {
    id: 3,
    name: "Smiley",
    tag: "smiley",
    color: "#5A4E42",
    topValue: -60,
  },
  {
    id: 4,
    name: "Wednesday",
    tag: "wednesday",
    color: "#81a2e8",
    topValue: 160,
  },
  {
    id:5,
    name: "Thumper",
    tag: "thumper",
    color: "#2A4F43",
    topValue: 80,
  },
  {
    id:6,
    name: "Junior",
    tag: "junior",
    color: "#333333",
    doublePfp: true,
    topValue: -80,
  },
  {
    id:7,
    name: "Temper",
    tag: "temper",
    color: "#FBC6B0",
    topValue: -70,
  },
  {
    id:8,
    name: "Zeke",
    tag: "zeke",
    color: "#8D9FC3",
    topValue: 80,
  },
  {
    id:9,
    name: "Rabbit",
    tag: "rabbit",
    color: "#D5738F",
    topValue: -65,
  },
  {
    id:10,
    name: "Flea",
    tag: "flea",
    color: "#555647",
    topValue: 140,
  },
  {
    id:11,
    name: "Lindo",
    tag: "lindo",
    color: "#B93D29",
    topValue: 80,
  },
  {
    id:12,
    name: "Nacho",
    tag: "nacho",
    color: "#8BD3D5",
    topValue: 190,
  },
  {
    id:13,
    name: "Canelo",
    tag: "canelo",
    color: "#FFB969",
    topValue: -90,
  },
  {
    id:14,
    name: "El Santo",
    tag: "el-santo",
    color: "#3969A2",
    topValue: -100,
  },
  {
    id:15,
    name: "Lobo",
    tag: "lobo",
    color: "#FFB969",
    topValue: 60,
  },
  {
    id:16,
    name: "Sonny",
    tag: "sonny",
    color: "#243250",
    topValue: -80,
  },
  {
    id:17,
    name: "Chido",
    tag: "chido",
    color: "#251C18",
    doublePfp: true,
    topValue: 120,
  },
  {
    id:18,
    name: "Flaco",
    tag: "flaco",
    color: "#FFCC00",
    topValue: 200,
  },
  {
    id:19,
    name: "Pablo",
    tag: "pablo",
    color: "#1E2738",
    topValue: -40,
  },
  {
    id:20,
    name: "Kahlo",
    tag: "kahlo",
    color: "#B7765B",
    topValue: -90,
  },
  {
    id:21,
    name: "Santi",
    tag: "santi",
    color: "#F76C31",
    topValue: 90,
  },
  {
    id:22,
    name: "Xolo",
    tag: "xolo",
    color: "#552433",
    topValue: -40,
  },
  {
    id:23,
    name: "Kai",
    tag: "kai",
    color: "#58C1BF",
    topValue: 40,
  },
  // {
  //   id:24,
  //   name: "Dark Kai",
  //   tag: "dark-kai",
  //   color: "#242424",
  //   topValue: 0,  
  // },
];